server:
  port: 9003

spring:
  application:
    name: cloudalibaba-payment-provider
  cloud:
    nacos:
      discovery:
      #nacos服务中心地址
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"