server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  # eureka 服务端的实例名称
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: false
#  server:
#    enable-self-preservation: false # 关闭eureka自我保护机制，保证不可用服务被及时剔除
#    eviction-interval-timer-in-ms: 2000
