server:
  port: 800
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: false
# 设置feign客户端超时时间（openFeign默认支持Ribbon）
ribbon:
#指的是建立来接所用的时间，使用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
#指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控那个接口
    com.cgs.springcloud.service.PaymentFeignService: debug